// deno-lint-ignore-file no-explicit-any
// the above line suppresses the linter from flagging 'any' type usage, since it seems like it is necessary for three.js
// if there are any further linting issues, i can tweak them to work better with three.js later if you let me know.
import * as THREE from "three";

// noah: the code below is just a basic Three.js script generated by Copilot for the sake of testing functionality
// please replace it later when we have our own code.

// Create scene
const scene = new THREE.Scene();

// Create camera
const camera = new THREE.PerspectiveCamera(
  75,
  globalThis.innerWidth / globalThis.innerHeight,
  0.1,
  1000,
);
(camera as any).position.z = 5;

// Create renderer
const renderer = new THREE.WebGLRenderer();
renderer.setSize(globalThis.innerWidth, globalThis.innerHeight);
document.body.appendChild(renderer.domElement as any);

// Create a cube
const geometry = new THREE.BoxGeometry();
const material = new THREE.MeshBasicMaterial({ color: 0x00ff00 });
const cube = new THREE.Mesh(geometry, material);
scene.add(cube as any);

// Animation loop
function animate() {
  requestAnimationFrame(animate);
  (cube as any).rotation.x += 0.01;
  (cube as any).rotation.y += 0.01;
  renderer.render(scene, camera);
}
animate();

// Handle globalThis resize
globalThis.addEventListener("resize", () => {
  camera.aspect = globalThis.innerWidth / globalThis.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(globalThis.innerWidth, globalThis.innerHeight);
});
